In [1]:
import numpy as np

In [2]:
T1 = np.arange(50)
T1.view()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [3]:
T2 = np.random.randint(0, 50, 50)
T2.view()

array([38, 32, 24, 49, 20, 26, 31, 18, 20, 47, 17, 10, 27, 25,  2, 12, 45,
       40, 11, 40, 46, 32, 22, 23, 48, 41, 18, 32, 32, 29, 22, 39, 24,  6,
       14, 44, 48, 43, 35, 43, 29, 24,  1, 33,  6, 20, 39, 44, 44, 38])

In [4]:
T3 = np.random.randn(50)
T3.view()

array([-0.02614949, -1.1624458 , -1.29343242, -0.12829562,  1.14117588,
       -0.91297161, -0.46125295,  0.29985892, -0.29690129, -2.13098551,
       -1.5186426 ,  0.54032952, -0.35512778,  0.40655598,  0.07814176,
       -0.67909284, -1.61080126,  1.23762671,  0.29052631,  1.00405632,
        2.15499197, -1.7715466 , -2.8915461 , -0.15850904, -0.26384017,
        0.31446877, -0.59556588, -0.42816963,  0.3662839 , -0.69523808,
       -0.37573168,  0.04676264, -1.19475888,  0.14564225, -0.0471913 ,
       -1.34479564,  0.02119466,  0.4246868 ,  0.40433337, -1.17755311,
       -0.63864422, -0.72195801,  1.00400899,  0.40997976,  0.20460053,
        2.0128841 ,  1.18169698,  1.18115797,  0.71110355, -2.92833688])